// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_prepair
Rcpp::CharacterVector rcpp_prepair(Rcpp::CharacterVector x, double min_area);
RcppExport SEXP _prepairr_rcpp_prepair(SEXP xSEXP, SEXP min_areaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type min_area(min_areaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_prepair(x, min_area));
    return rcpp_result_gen;
END_RCPP
}
